name: Open Telegram Bot

on:
  schedule:
    - cron: '1 */4 * * *'  # Запуск каждые 4 часа в 1 минуту
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: pip install pyrogram
          
      - name: Run Bot
        run: python bot.py
