name: Pyro Farm Bot

on:
  schedule:
    - cron: '0 */4 * * *'  # Каждые 4 часа (в 00:00, 04:00, 08:00 и т. д.)
  workflow_dispatch:  # Ручной запуск

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install pyrogram requests
      - name: Run Pyrogram Bot
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python bot.py
