name: Telegram Bot (4h1m from start)

on:
  workflow_dispatch:  # Только ручной запуск
  schedule:
    - cron: '0 */4 * * *'  # Резервный триггер каждые 4 часа

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: pip install pyrogram TgCrypto
          
      - name: Run persistent bot
        run: python bot.py
